// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lbqotzbwdfqddrgiurlu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxicW90emJ3ZGZxZGRyZ2l1cmx1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3Mzk2NDM1NTAsImV4cCI6MjA1NTIxOTU1MH0.lzFdkb9fghDh42PJLzcax3ugDyN9wQosQvt6BjvBUpo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);